### ISSUE TITLE
I'm having issues. Please help.

### ISSUE THREAD

**Issue by MishMish2024** [griffenx/Apex-Launcher#17]
The game keeps saying this. What do I do?
# Exception Details
System.IO.IOException: The process cannot access the file 'C:\Users\Xhavier\Downloads\Versions\ALPHA 6\Audio\BGM\OST Ambient Wind.wav' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at Apex_Launcher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.4.1.0
* Current Game Version: ALPHA 0.0
* Install Path: C:\Users\Xhavier\Downloads

# Files
* `config.txt`
* C:\Users\Xhavier\Downloads:
    * ALPHA 6:
        * Audio

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0

**Comment by griffenx** [comment]
Was this ticket closed because the problem was resolved? If so, could you share your solution, for future reference?
