### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FossilLovingMedic** [griffenx/Apex-Launcher#20]
# Exception Details
System.UnauthorizedAccessException: Access to the path 'C:\WINDOWS\system32\config.txt' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Apex_Launcher.Program.initialize()
   at Apex_Launcher.Program.Main()

# Configuration
* Current Launcher Version: 1.4.3.0

# Files

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0

**Comment by griffenx** [comment]
Where are you trying to run the .exe? It looks like the program is attempting to access your system32 folder, which should only happen if the .exe was placed there.

**Comment by griffenx** [comment]
Closed due to inactivity.
