### ISSUE TITLE
IOException During Unzip

### ISSUE THREAD

**Issue by KingAE** [griffenx/Apex-Launcher#21]
# Exception Details
System.IO.IOException: The process cannot access the file 'C:\Users\Malik Edwards\Downloads\Versions\ALPHA 7\Audio\SE\572Cry.wav' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at Apex_Launcher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.4.3.0
* Current Game Version: ALPHA 0.0
* Install Path: 

# Files
* `config.txt`

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0

**Comment by griffenx** [comment]
This seems like an odd error. Did you have the game files open in another program while it was attempting to extract them? Did this error occur again when you retried?

**Comment by griffenx** [comment]
Closing this issue due to lack of information.
