### ISSUE TITLE
File Access Error during Unzip

### ISSUE THREAD

**Issue by dragonstone481** [griffenx/Apex-Launcher#24]
# Exception Details
System.IO.IOException: The process cannot access the file 'C:\Users\b3nst\Downloads\Versions\ALPHA 7\Audio\SE\402Cry.wav' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at Apex_Launcher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.4.3.0
* Current Game Version: ALPHA 0.0
* Install Path: C:\Users\b3nst\Downloads

# Files
* `config.txt`
* C:\Users\b3nst\Downloads:
    * ALPHA 7:
        * Audio

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0

**Comment by griffenx** [comment]
Looks like you encountered this error while trying to unzip a download. Can you try it again and see if the issue persists?

**Comment by griffenx** [comment]
Closing due to inactivity. Reply to this message to reopen the issue if you have information to add.
