### ISSUE TITLE
Launcher attempts to load config.txt from system32

### ISSUE THREAD

**Issue by FluffyLeTryhard** [griffenx/Apex-Launcher#25]
# Exception Details
System.UnauthorizedAccessException: Access to the path 'C:\WINDOWS\system32\config.txt' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Apex_Launcher.Program.initialize()
   at Apex_Launcher.Program.Main()

# Configuration
* Current Launcher Version: 1.4.3.0

# Files

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0

**Comment by griffenx** [comment]
Can you provide more details? From what file location are you running the game?

**Comment by MrQuackerton** [comment]
Mine was running just fine. I played a total of 3 hours before I took a break and closed out of the game. I tried to open it through the downloads folder but that error popped up

**Comment by griffenx** [comment]
Does this happen every time you try to run the launcher, or just intermittently?

**Comment by MrQuackerton** [comment]
Every time I try to start the launcher

**Comment by griffenx** [comment]
Okay. I think I added a fix for this in a prior commit, but hadn't released it yet. If I send you an updated version that includes this fix, can you test it for me?

**Comment by MrQuackerton** [comment]
Yep. I’m currently not home right now but I’ll be home in about an hour and a half so I can download it then

**Comment by griffenx** [comment]
Try this version and see if it produces the same error:
[Apex Launcher.zip](https://github.com/griffenx/Apex-Launcher/files/2957249/Apex.Launcher.zip)

**Comment by MrQuackerton** [comment]
Alright it worked. Thank you

**Comment by griffenx** [comment]
Awesome. I'll go ahead and mark this issue as solved and close it. I'll be pushing out a new release shortly, so you'll be able to get the full fix soon.
